version: "3.8"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - server
            - mongo

    server:
        build: ./server
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=production
            - MONGO_URI=mongodb://mongo:27017/cars_market
        depends_on:
            - mongo
        volumes:
            - ./server/autos.csv:/app/autos.csv

    mongo:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"

    grafana:
        image: grafana/grafana:latest
        volumes:
            - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
        ports:
            - "3001:3000"
        depends_on:
            - prometheus

volumes:
    mongo-data:
